CREATE DATABASE IF NOT EXISTS CHURN_ML;
CREATE SCHEMA IF NOT EXISTS CHURN_ML.RAW;
CREATE SCHEMA IF NOT EXISTS CHURN_ML.FEATURE_STORE;
CREATE SCHEMA IF NOT EXISTS CHURN_ML.MONITORING;

CREATE WAREHOUSE IF NOT EXISTS ML_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE TABLE IF NOT EXISTS CHURN_ML.FEATURE_STORE.CUSTOMER_CHURN_FEATURES (
  customer_id STRING,
  monthly_recurring_revenue FLOAT,
  days_since_signup INTEGER,
  support_ticket_rate FLOAT,
  payment_failure_rate FLOAT,
  mrr_per_active_day FLOAT,
  feature_created_at TIMESTAMP_NTZ,
  PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS CHURN_ML.FEATURE_STORE.CUSTOMER_CHURN_FEATURES_ONLINE LIKE CHURN_ML.FEATURE_STORE.CUSTOMER_CHURN_FEATURES;

